echo -n acci.html >> outG.txt 	acci.html
echo -n anse.html >> outG.txt 	anse.html
echo -n apod.html >> outG.txt 	apod.html
echo -n apte.html >> outG.txt 	apte.html
echo -n buce.html >> outG.txt 	buce.html
echo -n capr.html >> outG.txt 	capr.html
echo -n cari.html >> outG.txt 	cari.html
echo -n casu.html >> outG.txt 	casu.html
echo -n char.html >> outG.txt 	char.html
echo -n cico.html >> outG.txt 	cico.html
echo -n coli.html >> outG.txt 	coli.html
echo -n colu.html >> outG.txt 	colu.html
echo -n cora.html >> outG.txt 	cora.html
echo -n cucu.html >> outG.txt 	cucu.html
echo -n eury.html >> outG.txt 	eury.html
echo -n falc.html >> outG.txt 	falc.html
echo -n galb.html >> outG.txt 	galb.html
echo -n gall.html >> outG.txt 	gall.html
echo -n gavi.html >> outG.txt 	gavi.html
echo -n grui.html >> outG.txt 	grui.html
echo -n lept.html >> outG.txt 	lept.html
echo -n mesi.html >> outG.txt 	mesi.html
echo -n muso.html >> outG.txt 	muso.html
echo -n nyct.html >> outG.txt 	nyct.html
echo -n opis.html >> outG.txt 	opis.html
echo -n otid.html >> outG.txt 	otid.html
echo -n pa01.html >> outG.txt 	pa01.html
echo -n pa02.html >> outG.txt 	pa02.html
echo -n pa03.html >> outG.txt 	pa03.html
echo -n pa05.html >> outG.txt 	pa05.html
echo -n pa06.html >> outG.txt 	pa06.html
echo -n pa07.html >> outG.txt 	pa07.html
echo -n pa08.html >> outG.txt 	pa08.html
echo -n pa09.html >> outG.txt 	pa09.html
echo -n pa0c.html >> outG.txt 	pa0c.html
echo -n pa10.html >> outG.txt 	pa10.html
echo -n pa13.html >> outG.txt 	pa13.html
echo -n pa1a.html >> outG.txt 	pa1a.html
echo -n pa1b.html >> outG.txt 	pa1b.html
echo -n pa1c.html >> outG.txt 	pa1c.html
echo -n pa1e.html >> outG.txt 	pa1e.html
echo -n pa1j.html >> outG.txt 	pa1j.html
echo -n pa1m.html >> outG.txt 	pa1m.html
echo -n pa1p.html >> outG.txt 	pa1p.html
echo -n pa1s.html >> outG.txt 	pa1s.html
echo -n pa1v.html >> outG.txt 	pa1v.html
echo -n pa1y.html >> outG.txt 	pa1y.html
echo -n pa20.html >> outG.txt 	pa20.html
echo -n pa21.html >> outG.txt 	pa21.html
echo -n pa22.html >> outG.txt 	pa22.html
echo -n pa23.html >> outG.txt 	pa23.html
echo -n pa24.html >> outG.txt 	pa24.html
echo -n pa25.html >> outG.txt 	pa25.html
echo -n pa26.html >> outG.txt 	pa26.html
echo -n pa27.html >> outG.txt 	pa27.html
echo -n pa28.html >> outG.txt 	pa28.html
echo -n pa29.html >> outG.txt 	pa29.html
echo -n pa2a.html >> outG.txt 	pa2a.html
echo -n pa2b.html >> outG.txt 	pa2b.html
echo -n pa2c.html >> outG.txt 	pa2c.html
echo -n pa2d.html >> outG.txt 	pa2d.html
echo -n pa2e.html >> outG.txt 	pa2e.html
echo -n pa2f.html >> outG.txt 	pa2f.html
echo -n pa2g.html >> outG.txt 	pa2g.html
echo -n pa2i.html >> outG.txt 	pa2i.html
echo -n pa2j.html >> outG.txt 	pa2j.html
echo -n pa2m.html >> outG.txt 	pa2m.html
echo -n pa2o.html >> outG.txt 	pa2o.html
echo -n pa2p.html >> outG.txt 	pa2p.html
echo -n pa2q.html >> outG.txt 	pa2q.html
echo -n pa2r.html >> outG.txt 	pa2r.html
echo -n pa2s.html >> outG.txt 	pa2s.html
echo -n pa2t.html >> outG.txt 	pa2t.html
echo -n pa2u.html >> outG.txt 	pa2u.html
echo -n pa2v.html >> outG.txt 	pa2v.html
echo -n pa2w.html >> outG.txt 	pa2w.html
echo -n pa2x.html >> outG.txt 	pa2x.html
echo -n pa2y.html >> outG.txt 	pa2y.html
echo -n pa2z.html >> outG.txt 	pa2z.html
echo -n pa30.html >> outG.txt 	pa30.html
echo -n pa31.html >> outG.txt 	pa31.html
echo -n pa32.html >> outG.txt 	pa32.html
echo -n pa33.html >> outG.txt 	pa33.html
echo -n pa34.html >> outG.txt 	pa34.html
echo -n pa35.html >> outG.txt 	pa35.html
echo -n pa36.html >> outG.txt 	pa36.html
echo -n pa37.html >> outG.txt 	pa37.html
echo -n pa38.html >> outG.txt 	pa38.html
echo -n pa39.html >> outG.txt 	pa39.html
echo -n pa3a.html >> outG.txt 	pa3a.html
echo -n pa3b.html >> outG.txt 	pa3b.html
echo -n pa3c.html >> outG.txt 	pa3c.html
echo -n pa3d.html >> outG.txt 	pa3d.html
echo -n pa3e.html >> outG.txt 	pa3e.html
echo -n pa3f.html >> outG.txt 	pa3f.html
echo -n pa3g.html >> outG.txt 	pa3g.html
echo -n pa3h.html >> outG.txt 	pa3h.html
echo -n pa3i.html >> outG.txt 	pa3i.html
echo -n pa3j.html >> outG.txt 	pa3j.html
echo -n pa3k.html >> outG.txt 	pa3k.html
echo -n pa3l.html >> outG.txt 	pa3l.html
echo -n pa3m.html >> outG.txt 	pa3m.html
echo -n pa3n.html >> outG.txt 	pa3n.html
echo -n pa3o.html >> outG.txt 	pa3o.html
echo -n pa3p.html >> outG.txt 	pa3p.html
echo -n pa3q.html >> outG.txt 	pa3q.html
echo -n pa3r.html >> outG.txt 	pa3r.html
echo -n pa3s.html >> outG.txt 	pa3s.html
echo -n pa3t.html >> outG.txt 	pa3t.html
echo -n pa3u.html >> outG.txt 	pa3u.html
echo -n pa3v.html >> outG.txt 	pa3v.html
echo -n pa3w.html >> outG.txt 	pa3w.html
echo -n pa3x.html >> outG.txt 	pa3x.html
echo -n pa3y.html >> outG.txt 	pa3y.html
echo -n pa3z.html >> outG.txt 	pa3z.html
echo -n pa40.html >> outG.txt 	pa40.html
echo -n pa41.html >> outG.txt 	pa41.html
echo -n pa42.html >> outG.txt 	pa42.html
echo -n pa43.html >> outG.txt 	pa43.html
echo -n pa44.html >> outG.txt 	pa44.html
echo -n pa45.html >> outG.txt 	pa45.html
echo -n pa46.html >> outG.txt 	pa46.html
echo -n pa47.html >> outG.txt 	pa47.html
echo -n pa48.html >> outG.txt 	pa48.html
echo -n pa49.html >> outG.txt 	pa49.html
echo -n pa4a.html >> outG.txt 	pa4a.html
echo -n pa4b.html >> outG.txt 	pa4b.html
echo -n pa4c.html >> outG.txt 	pa4c.html
echo -n pa4d.html >> outG.txt 	pa4d.html
echo -n pa4e.html >> outG.txt 	pa4e.html
echo -n pa4f.html >> outG.txt 	pa4f.html
echo -n pa4g.html >> outG.txt 	pa4g.html
echo -n pa4h.html >> outG.txt 	pa4h.html
echo -n pa4j.html >> outG.txt 	pa4j.html
echo -n pa4k.html >> outG.txt 	pa4k.html
echo -n pa4l.html >> outG.txt 	pa4l.html
echo -n pa4m.html >> outG.txt 	pa4m.html
echo -n pa4n.html >> outG.txt 	pa4n.html
echo -n pa4o.html >> outG.txt 	pa4o.html
echo -n pa4p.html >> outG.txt 	pa4p.html
echo -n pa4q.html >> outG.txt 	pa4q.html
echo -n pa4r.html >> outG.txt 	pa4r.html
echo -n pa4t.html >> outG.txt 	pa4t.html
echo -n pa4v.html >> outG.txt 	pa4v.html
echo -n pa4w.html >> outG.txt 	pa4w.html
echo -n pa4x.html >> outG.txt 	pa4x.html
echo -n pa4y.html >> outG.txt 	pa4y.html
echo -n pa50.html >> outG.txt 	pa50.html
echo -n pa51.html >> outG.txt 	pa51.html
echo -n pa52.html >> outG.txt 	pa52.html
echo -n pa53.html >> outG.txt 	pa53.html
echo -n pa60.html >> outG.txt 	pa60.html
echo -n pa61.html >> outG.txt 	pa61.html
echo -n pa63.html >> outG.txt 	pa63.html
echo -n pa64.html >> outG.txt 	pa64.html
echo -n pa65.html >> outG.txt 	pa65.html
echo -n pa66.html >> outG.txt 	pa66.html
echo -n pa6a.html >> outG.txt 	pa6a.html
echo -n pa6b.html >> outG.txt 	pa6b.html
echo -n pa6d.html >> outG.txt 	pa6d.html
echo -n pa6f.html >> outG.txt 	pa6f.html
echo -n pa6g.html >> outG.txt 	pa6g.html
echo -n pa6i.html >> outG.txt 	pa6i.html
echo -n pa6k.html >> outG.txt 	pa6k.html
echo -n pa6m.html >> outG.txt 	pa6m.html
echo -n pa6p.html >> outG.txt 	pa6p.html
echo -n pa6r.html >> outG.txt 	pa6r.html
echo -n pa6s.html >> outG.txt 	pa6s.html
echo -n pa6t.html >> outG.txt 	pa6t.html
echo -n pass.html >> outG.txt 	pass.html
echo -n pele.html >> outG.txt 	pele.html
echo -n phae.html >> outG.txt 	phae.html
echo -n phoe.html >> outG.txt 	phoe.html
echo -n pici.html >> outG.txt 	pici.html
echo -n podi.html >> outG.txt 	podi.html
echo -n proc.html >> outG.txt 	proc.html
echo -n psit.html >> outG.txt 	psit.html
echo -n pter.html >> outG.txt 	pter.html
echo -n rhei.html >> outG.txt 	rhei.html
echo -n sphe.html >> outG.txt 	sphe.html
echo -n stri.html >> outG.txt 	stri.html
echo -n stru.html >> outG.txt 	stru.html
echo -n suli.html >> outG.txt 	suli.html
echo -n tina.html >> outG.txt 	tina.html
echo -n trog.html >> outG.txt 	trog.html
