echo -n stru.html >> cntg01.txt ; egrep '^<h4' stru.html | wc -l >> cntg01.txt 
echo -n rhei.html >> cntg01.txt ; egrep '^<h4' rhei.html | wc -l >> cntg01.txt 
echo -n apte.html >> cntg01.txt ; egrep '^<h4' apte.html | wc -l >> cntg01.txt 
echo -n casu.html >> cntg01.txt ; egrep '^<h4' casu.html | wc -l >> cntg01.txt 
echo -n tina.html >> cntg01.txt ; egrep '^<h4' tina.html | wc -l >> cntg01.txt 
echo -n anse.html >> cntg01.txt ; egrep '^<h4' anse.html | wc -l >> cntg01.txt 
echo -n gall.html >> cntg01.txt ; egrep '^<h4' gall.html | wc -l >> cntg01.txt 
echo -n gavi.html >> cntg01.txt ; egrep '^<h4' gavi.html | wc -l >> cntg01.txt 
echo -n sphe.html >> cntg01.txt ; egrep '^<h4' sphe.html | wc -l >> cntg01.txt 
echo -n proc.html >> cntg01.txt ; egrep '^<h4' proc.html | wc -l >> cntg01.txt 
echo -n podi.html >> cntg01.txt ; egrep '^<h4' podi.html | wc -l >> cntg01.txt 
echo -n phoe.html >> cntg01.txt ; egrep '^<h4' phoe.html | wc -l >> cntg01.txt 
echo -n phae.html >> cntg01.txt ; egrep '^<h4' phae.html | wc -l >> cntg01.txt 
echo -n cico.html >> cntg01.txt ; egrep '^<h4' cico.html | wc -l >> cntg01.txt 
echo -n pele.html >> cntg01.txt ; egrep '^<h4' pele.html | wc -l >> cntg01.txt 
echo -n suli.html >> cntg01.txt ; egrep '^<h4' suli.html | wc -l >> cntg01.txt 
echo -n acci.html >> cntg01.txt ; egrep '^<h4' acci.html | wc -l >> cntg01.txt 
echo -n otid.html >> cntg01.txt ; egrep '^<h4' otid.html | wc -l >> cntg01.txt 
echo -n mesi.html >> cntg01.txt ; egrep '^<h4' mesi.html | wc -l >> cntg01.txt 
echo -n cari.html >> cntg01.txt ; egrep '^<h4' cari.html | wc -l >> cntg01.txt 
echo -n eury.html >> cntg01.txt ; egrep '^<h4' eury.html | wc -l >> cntg01.txt 
echo -n grui.html >> cntg01.txt ; egrep '^<h4' grui.html | wc -l >> cntg01.txt 
echo -n char.html >> cntg01.txt ; egrep '^<h4' char.html | wc -l >> cntg01.txt 
echo -n pter.html >> cntg01.txt ; egrep '^<h4' pter.html | wc -l >> cntg01.txt 
echo -n colu.html >> cntg01.txt ; egrep '^<h4' colu.html | wc -l >> cntg01.txt 
echo -n opis.html >> cntg01.txt ; egrep '^<h4' opis.html | wc -l >> cntg01.txt 
echo -n muso.html >> cntg01.txt ; egrep '^<h4' muso.html | wc -l >> cntg01.txt 
echo -n cucu.html >> cntg01.txt ; egrep '^<h4' cucu.html | wc -l >> cntg01.txt 
echo -n stri.html >> cntg01.txt ; egrep '^<h4' stri.html | wc -l >> cntg01.txt 
echo -n capr.html >> cntg01.txt ; egrep '^<h4' capr.html | wc -l >> cntg01.txt 
echo -n apod.html >> cntg01.txt ; egrep '^<h4' apod.html | wc -l >> cntg01.txt 
echo -n apod.html >> cntg01.txt ; egrep '^<h4' apod.html | wc -l >> cntg01.txt 
echo -n coli.html >> cntg01.txt ; egrep '^<h4' coli.html | wc -l >> cntg01.txt 
echo -n trog.html >> cntg01.txt ; egrep '^<h4' trog.html | wc -l >> cntg01.txt 
echo -n lept.html >> cntg01.txt ; egrep '^<h4' lept.html | wc -l >> cntg01.txt 
echo -n cora.html >> cntg01.txt ; egrep '^<h4' cora.html | wc -l >> cntg01.txt 
echo -n buce.html >> cntg01.txt ; egrep '^<h4' buce.html | wc -l >> cntg01.txt 
echo -n pici.html >> cntg01.txt ; egrep '^<h4' pici.html | wc -l >> cntg01.txt 
echo -n falc.html >> cntg01.txt ; egrep '^<h4' falc.html | wc -l >> cntg01.txt 
echo -n psit.html >> cntg01.txt ; egrep '^<h4' psit.html | wc -l >> cntg01.txt 
echo -n pass.html >> cntg01.txt ; egrep '^<h4' pass.html | wc -l >> cntg01.txt 
echo -n pa01.html >> cntg01.txt ; egrep '^<h4' pa01.html | wc -l >> cntg01.txt 
echo -n pa0c.html >> cntg01.txt ; egrep '^<h4' pa0c.html | wc -l >> cntg01.txt 
echo -n pa02.html >> cntg01.txt ; egrep '^<h4' pa02.html | wc -l >> cntg01.txt 
echo -n pa03.html >> cntg01.txt ; egrep '^<h4' pa03.html | wc -l >> cntg01.txt 
echo -n pa05.html >> cntg01.txt ; egrep '^<h4' pa05.html | wc -l >> cntg01.txt 
echo -n pa09.html >> cntg01.txt ; egrep '^<h4' pa09.html | wc -l >> cntg01.txt 
echo -n pa13.html >> cntg01.txt ; egrep '^<h4' pa13.html | wc -l >> cntg01.txt 
echo -n pa1e.html >> cntg01.txt ; egrep '^<h4' pa1e.html | wc -l >> cntg01.txt 
echo -n pa10.html >> cntg01.txt ; egrep '^<h4' pa10.html | wc -l >> cntg01.txt 
echo -n pa1a.html >> cntg01.txt ; egrep '^<h4' pa1a.html | wc -l >> cntg01.txt 
echo -n pa1b.html >> cntg01.txt ; egrep '^<h4' pa1b.html | wc -l >> cntg01.txt 
echo -n pa08.html >> cntg01.txt ; egrep '^<h4' pa08.html | wc -l >> cntg01.txt 
echo -n pa07.html >> cntg01.txt ; egrep '^<h4' pa07.html | wc -l >> cntg01.txt 
echo -n pa06.html >> cntg01.txt ; egrep '^<h4' pa06.html | wc -l >> cntg01.txt 
echo -n pa1c.html >> cntg01.txt ; egrep '^<h4' pa1c.html | wc -l >> cntg01.txt 
echo -n pa1j.html >> cntg01.txt ; egrep '^<h4' pa1j.html | wc -l >> cntg01.txt 
echo -n pa1m.html >> cntg01.txt ; egrep '^<h4' pa1m.html | wc -l >> cntg01.txt 
echo -n pa1p.html >> cntg01.txt ; egrep '^<h4' pa1p.html | wc -l >> cntg01.txt 
echo -n pa1s.html >> cntg01.txt ; egrep '^<h4' pa1s.html | wc -l >> cntg01.txt 
echo -n pa1v.html >> cntg01.txt ; egrep '^<h4' pa1v.html | wc -l >> cntg01.txt 
echo -n pa1y.html >> cntg01.txt ; egrep '^<h4' pa1y.html | wc -l >> cntg01.txt 
echo -n pa20.html >> cntg01.txt ; egrep '^<h4' pa20.html | wc -l >> cntg01.txt 
echo -n pa21.html >> cntg01.txt ; egrep '^<h4' pa21.html | wc -l >> cntg01.txt 
echo -n pa22.html >> cntg01.txt ; egrep '^<h4' pa22.html | wc -l >> cntg01.txt 
echo -n pa23.html >> cntg01.txt ; egrep '^<h4' pa23.html | wc -l >> cntg01.txt 
echo -n pa24.html >> cntg01.txt ; egrep '^<h4' pa24.html | wc -l >> cntg01.txt 
echo -n pa25.html >> cntg01.txt ; egrep '^<h4' pa25.html | wc -l >> cntg01.txt 
echo -n pa26.html >> cntg01.txt ; egrep '^<h4' pa26.html | wc -l >> cntg01.txt 
echo -n pa2f.html >> cntg01.txt ; egrep '^<h4' pa2f.html | wc -l >> cntg01.txt 
echo -n pa27.html >> cntg01.txt ; egrep '^<h4' pa27.html | wc -l >> cntg01.txt 
echo -n pa29.html >> cntg01.txt ; egrep '^<h4' pa29.html | wc -l >> cntg01.txt 
echo -n pa28.html >> cntg01.txt ; egrep '^<h4' pa28.html | wc -l >> cntg01.txt 
echo -n pa2a.html >> cntg01.txt ; egrep '^<h4' pa2a.html | wc -l >> cntg01.txt 
echo -n pa2b.html >> cntg01.txt ; egrep '^<h4' pa2b.html | wc -l >> cntg01.txt 
echo -n pa2e.html >> cntg01.txt ; egrep '^<h4' pa2e.html | wc -l >> cntg01.txt 
echo -n pa2g.html >> cntg01.txt ; egrep '^<h4' pa2g.html | wc -l >> cntg01.txt 
echo -n pa2c.html >> cntg01.txt ; egrep '^<h4' pa2c.html | wc -l >> cntg01.txt 
echo -n pa2d.html >> cntg01.txt ; egrep '^<h4' pa2d.html | wc -l >> cntg01.txt 
echo -n pa2o.html >> cntg01.txt ; egrep '^<h4' pa2o.html | wc -l >> cntg01.txt 
echo -n pa2i.html >> cntg01.txt ; egrep '^<h4' pa2i.html | wc -l >> cntg01.txt 
echo -n pa2j.html >> cntg01.txt ; egrep '^<h4' pa2j.html | wc -l >> cntg01.txt 
echo -n pa2m.html >> cntg01.txt ; egrep '^<h4' pa2m.html | wc -l >> cntg01.txt 
echo -n pa2q.html >> cntg01.txt ; egrep '^<h4' pa2q.html | wc -l >> cntg01.txt 
echo -n pa2s.html >> cntg01.txt ; egrep '^<h4' pa2s.html | wc -l >> cntg01.txt 
echo -n pa2u.html >> cntg01.txt ; egrep '^<h4' pa2u.html | wc -l >> cntg01.txt 
echo -n pa2w.html >> cntg01.txt ; egrep '^<h4' pa2w.html | wc -l >> cntg01.txt 
echo -n pa31.html >> cntg01.txt ; egrep '^<h4' pa31.html | wc -l >> cntg01.txt 
echo -n pa35.html >> cntg01.txt ; egrep '^<h4' pa35.html | wc -l >> cntg01.txt 
echo -n pa32.html >> cntg01.txt ; egrep '^<h4' pa32.html | wc -l >> cntg01.txt 
echo -n pa33.html >> cntg01.txt ; egrep '^<h4' pa33.html | wc -l >> cntg01.txt 
echo -n pa34.html >> cntg01.txt ; egrep '^<h4' pa34.html | wc -l >> cntg01.txt 
echo -n pa36.html >> cntg01.txt ; egrep '^<h4' pa36.html | wc -l >> cntg01.txt 
echo -n pa37.html >> cntg01.txt ; egrep '^<h4' pa37.html | wc -l >> cntg01.txt 
echo -n pa38.html >> cntg01.txt ; egrep '^<h4' pa38.html | wc -l >> cntg01.txt 
echo -n pa39.html >> cntg01.txt ; egrep '^<h4' pa39.html | wc -l >> cntg01.txt 
echo -n pa3a.html >> cntg01.txt ; egrep '^<h4' pa3a.html | wc -l >> cntg01.txt 
echo -n pa3b.html >> cntg01.txt ; egrep '^<h4' pa3b.html | wc -l >> cntg01.txt 
echo -n pa3d.html >> cntg01.txt ; egrep '^<h4' pa3d.html | wc -l >> cntg01.txt 
echo -n pa3c.html >> cntg01.txt ; egrep '^<h4' pa3c.html | wc -l >> cntg01.txt 
echo -n pa3e.html >> cntg01.txt ; egrep '^<h4' pa3e.html | wc -l >> cntg01.txt 
echo -n pa3g.html >> cntg01.txt ; egrep '^<h4' pa3g.html | wc -l >> cntg01.txt 
echo -n pa3h.html >> cntg01.txt ; egrep '^<h4' pa3h.html | wc -l >> cntg01.txt 
echo -n pa3j.html >> cntg01.txt ; egrep '^<h4' pa3j.html | wc -l >> cntg01.txt 
echo -n pa2p.html >> cntg01.txt ; egrep '^<h4' pa2p.html | wc -l >> cntg01.txt 
echo -n pa2r.html >> cntg01.txt ; egrep '^<h4' pa2r.html | wc -l >> cntg01.txt 
echo -n pa3i.html >> cntg01.txt ; egrep '^<h4' pa3i.html | wc -l >> cntg01.txt 
echo -n pa3k.html >> cntg01.txt ; egrep '^<h4' pa3k.html | wc -l >> cntg01.txt 
echo -n pa3l.html >> cntg01.txt ; egrep '^<h4' pa3l.html | wc -l >> cntg01.txt 
echo -n pa2t.html >> cntg01.txt ; egrep '^<h4' pa2t.html | wc -l >> cntg01.txt 
echo -n pa2x.html >> cntg01.txt ; egrep '^<h4' pa2x.html | wc -l >> cntg01.txt 
echo -n pa3n.html >> cntg01.txt ; egrep '^<h4' pa3n.html | wc -l >> cntg01.txt 
echo -n pa3o.html >> cntg01.txt ; egrep '^<h4' pa3o.html | wc -l >> cntg01.txt 
echo -n pa2v.html >> cntg01.txt ; egrep '^<h4' pa2v.html | wc -l >> cntg01.txt 
echo -n pa2y.html >> cntg01.txt ; egrep '^<h4' pa2y.html | wc -l >> cntg01.txt 
echo -n pa3u.html >> cntg01.txt ; egrep '^<h4' pa3u.html | wc -l >> cntg01.txt 
echo -n pa3x.html >> cntg01.txt ; egrep '^<h4' pa3x.html | wc -l >> cntg01.txt 
echo -n pa3q.html >> cntg01.txt ; egrep '^<h4' pa3q.html | wc -l >> cntg01.txt 
echo -n pa2z.html >> cntg01.txt ; egrep '^<h4' pa2z.html | wc -l >> cntg01.txt 
echo -n pa3y.html >> cntg01.txt ; egrep '^<h4' pa3y.html | wc -l >> cntg01.txt 
echo -n pa3r.html >> cntg01.txt ; egrep '^<h4' pa3r.html | wc -l >> cntg01.txt 
echo -n pa3f.html >> cntg01.txt ; egrep '^<h4' pa3f.html | wc -l >> cntg01.txt 
echo -n pa3m.html >> cntg01.txt ; egrep '^<h4' pa3m.html | wc -l >> cntg01.txt 
echo -n pa3p.html >> cntg01.txt ; egrep '^<h4' pa3p.html | wc -l >> cntg01.txt 
echo -n pa3p.html >> cntg01.txt ; egrep '^<h4' pa3p.html | wc -l >> cntg01.txt 
echo -n pa3s.html >> cntg01.txt ; egrep '^<h4' pa3s.html | wc -l >> cntg01.txt 
echo -n pa3t.html >> cntg01.txt ; egrep '^<h4' pa3t.html | wc -l >> cntg01.txt 
echo -n pa3w.html >> cntg01.txt ; egrep '^<h4' pa3w.html | wc -l >> cntg01.txt 
echo -n pa4a.html >> cntg01.txt ; egrep '^<h4' pa4a.html | wc -l >> cntg01.txt 
echo -n pa4q.html >> cntg01.txt ; egrep '^<h4' pa4q.html | wc -l >> cntg01.txt 
echo -n pa4c.html >> cntg01.txt ; egrep '^<h4' pa4c.html | wc -l >> cntg01.txt 
echo -n pa3v.html >> cntg01.txt ; egrep '^<h4' pa3v.html | wc -l >> cntg01.txt 
echo -n pa3z.html >> cntg01.txt ; egrep '^<h4' pa3z.html | wc -l >> cntg01.txt 
echo -n pa4e.html >> cntg01.txt ; egrep '^<h4' pa4e.html | wc -l >> cntg01.txt 
echo -n pa4g.html >> cntg01.txt ; egrep '^<h4' pa4g.html | wc -l >> cntg01.txt 
echo -n pa4h.html >> cntg01.txt ; egrep '^<h4' pa4h.html | wc -l >> cntg01.txt 
echo -n pa40.html >> cntg01.txt ; egrep '^<h4' pa40.html | wc -l >> cntg01.txt 
echo -n pa41.html >> cntg01.txt ; egrep '^<h4' pa41.html | wc -l >> cntg01.txt 
echo -n pa4m.html >> cntg01.txt ; egrep '^<h4' pa4m.html | wc -l >> cntg01.txt 
echo -n pa42.html >> cntg01.txt ; egrep '^<h4' pa42.html | wc -l >> cntg01.txt 
echo -n pa43.html >> cntg01.txt ; egrep '^<h4' pa43.html | wc -l >> cntg01.txt 
echo -n pa4k.html >> cntg01.txt ; egrep '^<h4' pa4k.html | wc -l >> cntg01.txt 
echo -n pa44.html >> cntg01.txt ; egrep '^<h4' pa44.html | wc -l >> cntg01.txt 
echo -n pa46.html >> cntg01.txt ; egrep '^<h4' pa46.html | wc -l >> cntg01.txt 
echo -n pa47.html >> cntg01.txt ; egrep '^<h4' pa47.html | wc -l >> cntg01.txt 
echo -n pa48.html >> cntg01.txt ; egrep '^<h4' pa48.html | wc -l >> cntg01.txt 
echo -n pa4n.html >> cntg01.txt ; egrep '^<h4' pa4n.html | wc -l >> cntg01.txt 
echo -n pa49.html >> cntg01.txt ; egrep '^<h4' pa49.html | wc -l >> cntg01.txt 
echo -n pa4b.html >> cntg01.txt ; egrep '^<h4' pa4b.html | wc -l >> cntg01.txt 
echo -n pa4d.html >> cntg01.txt ; egrep '^<h4' pa4d.html | wc -l >> cntg01.txt 
echo -n pa4f.html >> cntg01.txt ; egrep '^<h4' pa4f.html | wc -l >> cntg01.txt 
echo -n pa4j.html >> cntg01.txt ; egrep '^<h4' pa4j.html | wc -l >> cntg01.txt 
echo -n pa4l.html >> cntg01.txt ; egrep '^<h4' pa4l.html | wc -l >> cntg01.txt 
echo -n pa45.html >> cntg01.txt ; egrep '^<h4' pa45.html | wc -l >> cntg01.txt 
echo -n pa4p.html >> cntg01.txt ; egrep '^<h4' pa4p.html | wc -l >> cntg01.txt 
echo -n pa4r.html >> cntg01.txt ; egrep '^<h4' pa4r.html | wc -l >> cntg01.txt 
echo -n pa4t.html >> cntg01.txt ; egrep '^<h4' pa4t.html | wc -l >> cntg01.txt 
echo -n pa4v.html >> cntg01.txt ; egrep '^<h4' pa4v.html | wc -l >> cntg01.txt 
echo -n pa4w.html >> cntg01.txt ; egrep '^<h4' pa4w.html | wc -l >> cntg01.txt 
echo -n pa4x.html >> cntg01.txt ; egrep '^<h4' pa4x.html | wc -l >> cntg01.txt 
echo -n pa4y.html >> cntg01.txt ; egrep '^<h4' pa4y.html | wc -l >> cntg01.txt 
echo -n pa51.html >> cntg01.txt ; egrep '^<h4' pa51.html | wc -l >> cntg01.txt 
echo -n pa53.html >> cntg01.txt ; egrep '^<h4' pa53.html | wc -l >> cntg01.txt 
echo -n pa50.html >> cntg01.txt ; egrep '^<h4' pa50.html | wc -l >> cntg01.txt 
echo -n pa52.html >> cntg01.txt ; egrep '^<h4' pa52.html | wc -l >> cntg01.txt 
echo -n pa60.html >> cntg01.txt ; egrep '^<h4' pa60.html | wc -l >> cntg01.txt 
echo -n pa6a.html >> cntg01.txt ; egrep '^<h4' pa6a.html | wc -l >> cntg01.txt 
echo -n pa6b.html >> cntg01.txt ; egrep '^<h4' pa6b.html | wc -l >> cntg01.txt 
echo -n pa64.html >> cntg01.txt ; egrep '^<h4' pa64.html | wc -l >> cntg01.txt 
echo -n pa6d.html >> cntg01.txt ; egrep '^<h4' pa6d.html | wc -l >> cntg01.txt 
echo -n pa6f.html >> cntg01.txt ; egrep '^<h4' pa6f.html | wc -l >> cntg01.txt 
echo -n pa6g.html >> cntg01.txt ; egrep '^<h4' pa6g.html | wc -l >> cntg01.txt 
echo -n pa6i.html >> cntg01.txt ; egrep '^<h4' pa6i.html | wc -l >> cntg01.txt 
echo -n pa6k.html >> cntg01.txt ; egrep '^<h4' pa6k.html | wc -l >> cntg01.txt 
echo -n pa6m.html >> cntg01.txt ; egrep '^<h4' pa6m.html | wc -l >> cntg01.txt 
echo -n pa6p.html >> cntg01.txt ; egrep '^<h4' pa6p.html | wc -l >> cntg01.txt 
echo -n pa6r.html >> cntg01.txt ; egrep '^<h4' pa6r.html | wc -l >> cntg01.txt 
echo -n pa6s.html >> cntg01.txt ; egrep '^<h4' pa6s.html | wc -l >> cntg01.txt 
echo -n pa61.html >> cntg01.txt ; egrep '^<h4' pa61.html | wc -l >> cntg01.txt 
echo -n pa6t.html >> cntg01.txt ; egrep '^<h4' pa6t.html | wc -l >> cntg01.txt 
echo -n pa65.html >> cntg01.txt ; egrep '^<h4' pa65.html | wc -l >> cntg01.txt 
echo -n pa66.html >> cntg01.txt ; egrep '^<h4' pa66.html | wc -l >> cntg01.txt 
