echo -n stru.html >> cnts01.txt ; egrep '^<li' stru.html | wc -l >> cnts01.txt 
echo -n rhei.html >> cnts01.txt ; egrep '^<li' rhei.html | wc -l >> cnts01.txt 
echo -n apte.html >> cnts01.txt ; egrep '^<li' apte.html | wc -l >> cnts01.txt 
echo -n casu.html >> cnts01.txt ; egrep '^<li' casu.html | wc -l >> cnts01.txt 
echo -n tina.html >> cnts01.txt ; egrep '^<li' tina.html | wc -l >> cnts01.txt 
echo -n anse.html >> cnts01.txt ; egrep '^<li' anse.html | wc -l >> cnts01.txt 
echo -n gall.html >> cnts01.txt ; egrep '^<li' gall.html | wc -l >> cnts01.txt 
echo -n gavi.html >> cnts01.txt ; egrep '^<li' gavi.html | wc -l >> cnts01.txt 
echo -n sphe.html >> cnts01.txt ; egrep '^<li' sphe.html | wc -l >> cnts01.txt 
echo -n proc.html >> cnts01.txt ; egrep '^<li' proc.html | wc -l >> cnts01.txt 
echo -n podi.html >> cnts01.txt ; egrep '^<li' podi.html | wc -l >> cnts01.txt 
echo -n phoe.html >> cnts01.txt ; egrep '^<li' phoe.html | wc -l >> cnts01.txt 
echo -n phae.html >> cnts01.txt ; egrep '^<li' phae.html | wc -l >> cnts01.txt 
echo -n cico.html >> cnts01.txt ; egrep '^<li' cico.html | wc -l >> cnts01.txt 
echo -n pele.html >> cnts01.txt ; egrep '^<li' pele.html | wc -l >> cnts01.txt 
echo -n suli.html >> cnts01.txt ; egrep '^<li' suli.html | wc -l >> cnts01.txt 
echo -n acci.html >> cnts01.txt ; egrep '^<li' acci.html | wc -l >> cnts01.txt 
echo -n otid.html >> cnts01.txt ; egrep '^<li' otid.html | wc -l >> cnts01.txt 
echo -n mesi.html >> cnts01.txt ; egrep '^<li' mesi.html | wc -l >> cnts01.txt 
echo -n cari.html >> cnts01.txt ; egrep '^<li' cari.html | wc -l >> cnts01.txt 
echo -n eury.html >> cnts01.txt ; egrep '^<li' eury.html | wc -l >> cnts01.txt 
echo -n grui.html >> cnts01.txt ; egrep '^<li' grui.html | wc -l >> cnts01.txt 
echo -n char.html >> cnts01.txt ; egrep '^<li' char.html | wc -l >> cnts01.txt 
echo -n pter.html >> cnts01.txt ; egrep '^<li' pter.html | wc -l >> cnts01.txt 
echo -n colu.html >> cnts01.txt ; egrep '^<li' colu.html | wc -l >> cnts01.txt 
echo -n opis.html >> cnts01.txt ; egrep '^<li' opis.html | wc -l >> cnts01.txt 
echo -n muso.html >> cnts01.txt ; egrep '^<li' muso.html | wc -l >> cnts01.txt 
echo -n cucu.html >> cnts01.txt ; egrep '^<li' cucu.html | wc -l >> cnts01.txt 
echo -n stri.html >> cnts01.txt ; egrep '^<li' stri.html | wc -l >> cnts01.txt 
echo -n capr.html >> cnts01.txt ; egrep '^<li' capr.html | wc -l >> cnts01.txt 
echo -n apod.html >> cnts01.txt ; egrep '^<li' apod.html | wc -l >> cnts01.txt 
echo -n coli.html >> cnts01.txt ; egrep '^<li' coli.html | wc -l >> cnts01.txt 
echo -n trog.html >> cnts01.txt ; egrep '^<li' trog.html | wc -l >> cnts01.txt 
echo -n lept.html >> cnts01.txt ; egrep '^<li' lept.html | wc -l >> cnts01.txt 
echo -n cora.html >> cnts01.txt ; egrep '^<li' cora.html | wc -l >> cnts01.txt 
echo -n buce.html >> cnts01.txt ; egrep '^<li' buce.html | wc -l >> cnts01.txt 
echo -n pici.html >> cnts01.txt ; egrep '^<li' pici.html | wc -l >> cnts01.txt 
echo -n falc.html >> cnts01.txt ; egrep '^<li' falc.html | wc -l >> cnts01.txt 
echo -n psit.html >> cnts01.txt ; egrep '^<li' psit.html | wc -l >> cnts01.txt 
echo -n pass.html >> cnts01.txt ; egrep '^<li' pass.html | wc -l >> cnts01.txt 
echo -n pa01.html >> cnts01.txt ; egrep '^<li' pa01.html | wc -l >> cnts01.txt 
echo -n pa0c.html >> cnts01.txt ; egrep '^<li' pa0c.html | wc -l >> cnts01.txt 
echo -n pa02.html >> cnts01.txt ; egrep '^<li' pa02.html | wc -l >> cnts01.txt 
echo -n pa03.html >> cnts01.txt ; egrep '^<li' pa03.html | wc -l >> cnts01.txt 
echo -n pa05.html >> cnts01.txt ; egrep '^<li' pa05.html | wc -l >> cnts01.txt 
echo -n pa09.html >> cnts01.txt ; egrep '^<li' pa09.html | wc -l >> cnts01.txt 
echo -n pa13.html >> cnts01.txt ; egrep '^<li' pa13.html | wc -l >> cnts01.txt 
echo -n pa1e.html >> cnts01.txt ; egrep '^<li' pa1e.html | wc -l >> cnts01.txt 
echo -n pa10.html >> cnts01.txt ; egrep '^<li' pa10.html | wc -l >> cnts01.txt 
echo -n pa1a.html >> cnts01.txt ; egrep '^<li' pa1a.html | wc -l >> cnts01.txt 
echo -n pa1b.html >> cnts01.txt ; egrep '^<li' pa1b.html | wc -l >> cnts01.txt 
echo -n pa08.html >> cnts01.txt ; egrep '^<li' pa08.html | wc -l >> cnts01.txt 
echo -n pa07.html >> cnts01.txt ; egrep '^<li' pa07.html | wc -l >> cnts01.txt 
echo -n pa06.html >> cnts01.txt ; egrep '^<li' pa06.html | wc -l >> cnts01.txt 
echo -n pa1c.html >> cnts01.txt ; egrep '^<li' pa1c.html | wc -l >> cnts01.txt 
echo -n pa1j.html >> cnts01.txt ; egrep '^<li' pa1j.html | wc -l >> cnts01.txt 
echo -n pa1m.html >> cnts01.txt ; egrep '^<li' pa1m.html | wc -l >> cnts01.txt 
echo -n pa1p.html >> cnts01.txt ; egrep '^<li' pa1p.html | wc -l >> cnts01.txt 
echo -n pa1s.html >> cnts01.txt ; egrep '^<li' pa1s.html | wc -l >> cnts01.txt 
echo -n pa1v.html >> cnts01.txt ; egrep '^<li' pa1v.html | wc -l >> cnts01.txt 
echo -n pa1y.html >> cnts01.txt ; egrep '^<li' pa1y.html | wc -l >> cnts01.txt 
echo -n pa20.html >> cnts01.txt ; egrep '^<li' pa20.html | wc -l >> cnts01.txt 
echo -n pa21.html >> cnts01.txt ; egrep '^<li' pa21.html | wc -l >> cnts01.txt 
echo -n pa22.html >> cnts01.txt ; egrep '^<li' pa22.html | wc -l >> cnts01.txt 
echo -n pa23.html >> cnts01.txt ; egrep '^<li' pa23.html | wc -l >> cnts01.txt 
echo -n pa24.html >> cnts01.txt ; egrep '^<li' pa24.html | wc -l >> cnts01.txt 
echo -n pa25.html >> cnts01.txt ; egrep '^<li' pa25.html | wc -l >> cnts01.txt 
echo -n pa26.html >> cnts01.txt ; egrep '^<li' pa26.html | wc -l >> cnts01.txt 
echo -n pa2f.html >> cnts01.txt ; egrep '^<li' pa2f.html | wc -l >> cnts01.txt 
echo -n pa27.html >> cnts01.txt ; egrep '^<li' pa27.html | wc -l >> cnts01.txt 
echo -n pa29.html >> cnts01.txt ; egrep '^<li' pa29.html | wc -l >> cnts01.txt 
echo -n pa28.html >> cnts01.txt ; egrep '^<li' pa28.html | wc -l >> cnts01.txt 
echo -n pa2a.html >> cnts01.txt ; egrep '^<li' pa2a.html | wc -l >> cnts01.txt 
echo -n pa2b.html >> cnts01.txt ; egrep '^<li' pa2b.html | wc -l >> cnts01.txt 
echo -n pa2e.html >> cnts01.txt ; egrep '^<li' pa2e.html | wc -l >> cnts01.txt 
echo -n pa2g.html >> cnts01.txt ; egrep '^<li' pa2g.html | wc -l >> cnts01.txt 
echo -n pa2c.html >> cnts01.txt ; egrep '^<li' pa2c.html | wc -l >> cnts01.txt 
echo -n pa2d.html >> cnts01.txt ; egrep '^<li' pa2d.html | wc -l >> cnts01.txt 
echo -n pa2o.html >> cnts01.txt ; egrep '^<li' pa2o.html | wc -l >> cnts01.txt 
echo -n pa2i.html >> cnts01.txt ; egrep '^<li' pa2i.html | wc -l >> cnts01.txt 
echo -n pa2j.html >> cnts01.txt ; egrep '^<li' pa2j.html | wc -l >> cnts01.txt 
echo -n pa2m.html >> cnts01.txt ; egrep '^<li' pa2m.html | wc -l >> cnts01.txt 
echo -n pa2q.html >> cnts01.txt ; egrep '^<li' pa2q.html | wc -l >> cnts01.txt 
echo -n pa2s.html >> cnts01.txt ; egrep '^<li' pa2s.html | wc -l >> cnts01.txt 
echo -n pa2u.html >> cnts01.txt ; egrep '^<li' pa2u.html | wc -l >> cnts01.txt 
echo -n pa2w.html >> cnts01.txt ; egrep '^<li' pa2w.html | wc -l >> cnts01.txt 
echo -n pa31.html >> cnts01.txt ; egrep '^<li' pa31.html | wc -l >> cnts01.txt 
echo -n pa35.html >> cnts01.txt ; egrep '^<li' pa35.html | wc -l >> cnts01.txt 
echo -n pa32.html >> cnts01.txt ; egrep '^<li' pa32.html | wc -l >> cnts01.txt 
echo -n pa33.html >> cnts01.txt ; egrep '^<li' pa33.html | wc -l >> cnts01.txt 
echo -n pa34.html >> cnts01.txt ; egrep '^<li' pa34.html | wc -l >> cnts01.txt 
echo -n pa36.html >> cnts01.txt ; egrep '^<li' pa36.html | wc -l >> cnts01.txt 
echo -n pa37.html >> cnts01.txt ; egrep '^<li' pa37.html | wc -l >> cnts01.txt 
echo -n pa38.html >> cnts01.txt ; egrep '^<li' pa38.html | wc -l >> cnts01.txt 
echo -n pa39.html >> cnts01.txt ; egrep '^<li' pa39.html | wc -l >> cnts01.txt 
echo -n pa3a.html >> cnts01.txt ; egrep '^<li' pa3a.html | wc -l >> cnts01.txt 
echo -n pa3b.html >> cnts01.txt ; egrep '^<li' pa3b.html | wc -l >> cnts01.txt 
echo -n pa3d.html >> cnts01.txt ; egrep '^<li' pa3d.html | wc -l >> cnts01.txt 
echo -n pa3c.html >> cnts01.txt ; egrep '^<li' pa3c.html | wc -l >> cnts01.txt 
echo -n pa3e.html >> cnts01.txt ; egrep '^<li' pa3e.html | wc -l >> cnts01.txt 
echo -n pa3g.html >> cnts01.txt ; egrep '^<li' pa3g.html | wc -l >> cnts01.txt 
echo -n pa3h.html >> cnts01.txt ; egrep '^<li' pa3h.html | wc -l >> cnts01.txt 
echo -n pa3j.html >> cnts01.txt ; egrep '^<li' pa3j.html | wc -l >> cnts01.txt 
echo -n pa2p.html >> cnts01.txt ; egrep '^<li' pa2p.html | wc -l >> cnts01.txt 
echo -n pa2r.html >> cnts01.txt ; egrep '^<li' pa2r.html | wc -l >> cnts01.txt 
echo -n pa3i.html >> cnts01.txt ; egrep '^<li' pa3i.html | wc -l >> cnts01.txt 
echo -n pa3k.html >> cnts01.txt ; egrep '^<li' pa3k.html | wc -l >> cnts01.txt 
echo -n pa3l.html >> cnts01.txt ; egrep '^<li' pa3l.html | wc -l >> cnts01.txt 
echo -n pa2t.html >> cnts01.txt ; egrep '^<li' pa2t.html | wc -l >> cnts01.txt 
echo -n pa2x.html >> cnts01.txt ; egrep '^<li' pa2x.html | wc -l >> cnts01.txt 
echo -n pa3n.html >> cnts01.txt ; egrep '^<li' pa3n.html | wc -l >> cnts01.txt 
echo -n pa3o.html >> cnts01.txt ; egrep '^<li' pa3o.html | wc -l >> cnts01.txt 
echo -n pa2v.html >> cnts01.txt ; egrep '^<li' pa2v.html | wc -l >> cnts01.txt 
echo -n pa2y.html >> cnts01.txt ; egrep '^<li' pa2y.html | wc -l >> cnts01.txt 
echo -n pa3u.html >> cnts01.txt ; egrep '^<li' pa3u.html | wc -l >> cnts01.txt 
echo -n pa3x.html >> cnts01.txt ; egrep '^<li' pa3x.html | wc -l >> cnts01.txt 
echo -n pa3q.html >> cnts01.txt ; egrep '^<li' pa3q.html | wc -l >> cnts01.txt 
echo -n pa2z.html >> cnts01.txt ; egrep '^<li' pa2z.html | wc -l >> cnts01.txt 
echo -n pa3y.html >> cnts01.txt ; egrep '^<li' pa3y.html | wc -l >> cnts01.txt 
echo -n pa3r.html >> cnts01.txt ; egrep '^<li' pa3r.html | wc -l >> cnts01.txt 
echo -n pa3f.html >> cnts01.txt ; egrep '^<li' pa3f.html | wc -l >> cnts01.txt 
echo -n pa3m.html >> cnts01.txt ; egrep '^<li' pa3m.html | wc -l >> cnts01.txt 
echo -n pa3p.html >> cnts01.txt ; egrep '^<li' pa3p.html | wc -l >> cnts01.txt 
echo -n pa3p.html >> cnts01.txt ; egrep '^<li' pa3p.html | wc -l >> cnts01.txt 
echo -n pa3s.html >> cnts01.txt ; egrep '^<li' pa3s.html | wc -l >> cnts01.txt 
echo -n pa3t.html >> cnts01.txt ; egrep '^<li' pa3t.html | wc -l >> cnts01.txt 
echo -n pa3w.html >> cnts01.txt ; egrep '^<li' pa3w.html | wc -l >> cnts01.txt 
echo -n pa4a.html >> cnts01.txt ; egrep '^<li' pa4a.html | wc -l >> cnts01.txt 
echo -n pa4q.html >> cnts01.txt ; egrep '^<li' pa4q.html | wc -l >> cnts01.txt 
echo -n pa4c.html >> cnts01.txt ; egrep '^<li' pa4c.html | wc -l >> cnts01.txt 
echo -n pa3v.html >> cnts01.txt ; egrep '^<li' pa3v.html | wc -l >> cnts01.txt 
echo -n pa3z.html >> cnts01.txt ; egrep '^<li' pa3z.html | wc -l >> cnts01.txt 
echo -n pa4e.html >> cnts01.txt ; egrep '^<li' pa4e.html | wc -l >> cnts01.txt 
echo -n pa4g.html >> cnts01.txt ; egrep '^<li' pa4g.html | wc -l >> cnts01.txt 
echo -n pa4h.html >> cnts01.txt ; egrep '^<li' pa4h.html | wc -l >> cnts01.txt 
echo -n pa40.html >> cnts01.txt ; egrep '^<li' pa40.html | wc -l >> cnts01.txt 
echo -n pa41.html >> cnts01.txt ; egrep '^<li' pa41.html | wc -l >> cnts01.txt 
echo -n pa4m.html >> cnts01.txt ; egrep '^<li' pa4m.html | wc -l >> cnts01.txt 
echo -n pa42.html >> cnts01.txt ; egrep '^<li' pa42.html | wc -l >> cnts01.txt 
echo -n pa43.html >> cnts01.txt ; egrep '^<li' pa43.html | wc -l >> cnts01.txt 
echo -n pa4k.html >> cnts01.txt ; egrep '^<li' pa4k.html | wc -l >> cnts01.txt 
echo -n pa44.html >> cnts01.txt ; egrep '^<li' pa44.html | wc -l >> cnts01.txt 
echo -n pa46.html >> cnts01.txt ; egrep '^<li' pa46.html | wc -l >> cnts01.txt 
echo -n pa47.html >> cnts01.txt ; egrep '^<li' pa47.html | wc -l >> cnts01.txt 
echo -n pa48.html >> cnts01.txt ; egrep '^<li' pa48.html | wc -l >> cnts01.txt 
echo -n pa4n.html >> cnts01.txt ; egrep '^<li' pa4n.html | wc -l >> cnts01.txt 
echo -n pa49.html >> cnts01.txt ; egrep '^<li' pa49.html | wc -l >> cnts01.txt 
echo -n pa4b.html >> cnts01.txt ; egrep '^<li' pa4b.html | wc -l >> cnts01.txt 
echo -n pa4d.html >> cnts01.txt ; egrep '^<li' pa4d.html | wc -l >> cnts01.txt 
echo -n pa4f.html >> cnts01.txt ; egrep '^<li' pa4f.html | wc -l >> cnts01.txt 
echo -n pa4j.html >> cnts01.txt ; egrep '^<li' pa4j.html | wc -l >> cnts01.txt 
echo -n pa4l.html >> cnts01.txt ; egrep '^<li' pa4l.html | wc -l >> cnts01.txt 
echo -n pa45.html >> cnts01.txt ; egrep '^<li' pa45.html | wc -l >> cnts01.txt 
echo -n pa4p.html >> cnts01.txt ; egrep '^<li' pa4p.html | wc -l >> cnts01.txt 
echo -n pa4r.html >> cnts01.txt ; egrep '^<li' pa4r.html | wc -l >> cnts01.txt 
echo -n pa4t.html >> cnts01.txt ; egrep '^<li' pa4t.html | wc -l >> cnts01.txt 
echo -n pa4v.html >> cnts01.txt ; egrep '^<li' pa4v.html | wc -l >> cnts01.txt 
echo -n pa4w.html >> cnts01.txt ; egrep '^<li' pa4w.html | wc -l >> cnts01.txt 
echo -n pa4x.html >> cnts01.txt ; egrep '^<li' pa4x.html | wc -l >> cnts01.txt 
echo -n pa4y.html >> cnts01.txt ; egrep '^<li' pa4y.html | wc -l >> cnts01.txt 
echo -n pa51.html >> cnts01.txt ; egrep '^<li' pa51.html | wc -l >> cnts01.txt 
echo -n pa53.html >> cnts01.txt ; egrep '^<li' pa53.html | wc -l >> cnts01.txt 
echo -n pa50.html >> cnts01.txt ; egrep '^<li' pa50.html | wc -l >> cnts01.txt 
echo -n pa52.html >> cnts01.txt ; egrep '^<li' pa52.html | wc -l >> cnts01.txt 
echo -n pa60.html >> cnts01.txt ; egrep '^<li' pa60.html | wc -l >> cnts01.txt 
echo -n pa6a.html >> cnts01.txt ; egrep '^<li' pa6a.html | wc -l >> cnts01.txt 
echo -n pa6b.html >> cnts01.txt ; egrep '^<li' pa6b.html | wc -l >> cnts01.txt 
echo -n pa64.html >> cnts01.txt ; egrep '^<li' pa64.html | wc -l >> cnts01.txt 
echo -n pa6d.html >> cnts01.txt ; egrep '^<li' pa6d.html | wc -l >> cnts01.txt 
echo -n pa6f.html >> cnts01.txt ; egrep '^<li' pa6f.html | wc -l >> cnts01.txt 
echo -n pa6g.html >> cnts01.txt ; egrep '^<li' pa6g.html | wc -l >> cnts01.txt 
echo -n pa6i.html >> cnts01.txt ; egrep '^<li' pa6i.html | wc -l >> cnts01.txt 
echo -n pa6k.html >> cnts01.txt ; egrep '^<li' pa6k.html | wc -l >> cnts01.txt 
echo -n pa6m.html >> cnts01.txt ; egrep '^<li' pa6m.html | wc -l >> cnts01.txt 
echo -n pa6p.html >> cnts01.txt ; egrep '^<li' pa6p.html | wc -l >> cnts01.txt 
echo -n pa6r.html >> cnts01.txt ; egrep '^<li' pa6r.html | wc -l >> cnts01.txt 
echo -n pa6s.html >> cnts01.txt ; egrep '^<li' pa6s.html | wc -l >> cnts01.txt 
echo -n pa61.html >> cnts01.txt ; egrep '^<li' pa61.html | wc -l >> cnts01.txt 
echo -n pa6t.html >> cnts01.txt ; egrep '^<li' pa6t.html | wc -l >> cnts01.txt 
echo -n pa65.html >> cnts01.txt ; egrep '^<li' pa65.html | wc -l >> cnts01.txt 
echo -n pa66.html >> cnts01.txt ; egrep '^<li' pa66.html | wc -l >> cnts01.txt 
